export const dummy_qna = [
  {
    qnaId: "q1",
    title: "How to use google analytics with next.js app?",
    content:
      "I'm using styled-components with next.js so my styles need to be server-side rendered, hence how can I add google analytics to my website? I checked next.js google analytics example but as I said my _document file is different because of using styled-components.",
    recommendations: [
      "userID_1",
      "userID_2",
      "userID_3",
      "userID_4",
      "userID_5",
      "userID_6",
      "userID_7",
      "userID_8",
      "userID_9",
      "userID_10",
    ],
    tags: ["next.js", "styled-components", "google-analytics"],
    user: "userID_A",
    date: new Date(),
    isAnswer: false,
    parentQuestion: null,
  },
  {
    qnaId: "q2",
    title: "ReactJS - Can't type on input fields",
    content:
      "I'm having an issue with the typing on input fields.. i'm working on a big project, which already had other input fields, which were working at the time i wrote them.. today i was adding new fields and noticed that the old fields didn't accept any kind of input. I know this a common question, but my problem is neither not having the value or the onChange set.  Here is a example of the new fields i was working on.",
    recommendations: [
      "userID_1",
      "userID_2",
      "userID_3",
      "userID_4",
      "userID_5",
      "userID_6",
      "userID_7",
      "userID_8",
    ],
    tags: ["react.js", "input"],
    user: "userID_B",
    date: new Date(),
    isAnswer: false,
    parentQuestion: null,
  },
  {
    qnaId: "q3",
    title: "Python data structures 2D lists",
    content:
      "Here is the question:Create a function that takes a grid of # and -, where each hash (#) represents a mine and each dash (-) represents a mine-free spot. Return a grid, where each dash is replaced by a digit, indicating the number of mines immediately adjacent to the spot i.e. (horizontally, vertically, and diagonally).",
    recommendations: ["userID_1", "userID_2"],
    tags: ["react.js", "input"],
    user: "userID_B",
    date: new Date(),
    isAnswer: false,
    parentQuestion: null,
  },
  {
    qnaId: "q4",
    title: "리액트로 검색 기능을 어떻게 구현할 수 있나요?",
    content:
      "이번 팀 프로젝트에서 검색 기능을 구현하게 되었는데 그냥 단순히 array.filter를 활용해 검색 기능을 구현하는 방법 말고 더 나은 방법이나 다른 방법에 대해 조언해주실 것이 있나요.",
    recommendations: [
      "userID_1",
      "userID_2",
      "userID_3",
      "userID_4",
      "userID_5",
      "userID_6",
      "userID_7",
      "userID_8",
      "userID_9",
      "userID_10",
      "userID_11",
      "userID_12",
      "userID_13",
      "userID_14",
      "userID_15",
    ],
    tags: ["react.js", "filter", "검색", "search"],
    user: "userID_C",
    date: new Date(),
    isAnswer: false,
    parentQuestion: null,
  },
  {
    qnaId: "q5",
    title:
      "react-editor-js를 활용해서 에디터를 구현하고자 하는데 이미지가 제대로 저장이 안되네요ㅠㅠ",
    content:
      "react-editor-js를 활용해서 에디터를 구현하고자 하는데 이미지가 제대로 저장이 안되네요ㅠㅠ 어떻게 하면 좋을 지 예시 내놔",
    recommendations: ["userID_1", "userID_2", "userID_12", "userID_13", "userID_14", "userID_15"],
    tags: [
      "react-editor-js",
      "emotion.js",
      "Editor.js",
      "next.js",
      "async",
      "examples",
      "에디터",
      "이미지",
    ],
    user: "userID_C",
    date: new Date(),
    isAnswer: false,
    parentQuestion: null,
  },
  {
    qnaId: "q6",
    title: "22222222222222 How to use google analytics with next.js app?",
    content:
      "I'm using styled-components with next.js so my styles need to be server-side rendered, hence how can I add google analytics to my website? I checked next.js google analytics example but as I said my _document file is different because of using styled-components.",
    recommendations: [
      "userID_1",
      "userID_2",
      "userID_3",
      "userID_4",
      "userID_5",
      "userID_6",
      "userID_7",
      "userID_8",
      "userID_9",
      "userID_10",
    ],
    tags: ["next.js", "styled-components", "google-analytics"],
    user: "userID_A",
    date: new Date(),
    isAnswer: false,
    parentQuestion: null,
  },
  {
    qnaId: "q7",
    title: "22222222222 ReactJS - Can't type on input fields",
    content:
      "I'm having an issue with the typing on input fields.. i'm working on a big project, which already had other input fields, which were working at the time i wrote them.. today i was adding new fields and noticed that the old fields didn't accept any kind of input. I know this a common question, but my problem is neither not having the value or the onChange set.  Here is a example of the new fields i was working on.",
    recommendations: [
      "userID_1",
      "userID_2",
      "userID_3",
      "userID_4",
      "userID_5",
      "userID_6",
      "userID_7",
      "userID_8",
    ],
    tags: ["react.js", "input"],
    user: "userID_B",
    date: new Date(),
    isAnswer: false,
    parentQuestion: null,
  },
  {
    qnaId: "q8",
    title: "2222222222 Python data structures 2D lists",
    content:
      "Here is the question:Create a function that takes a grid of # and -, where each hash (#) represents a mine and each dash (-) represents a mine-free spot. Return a grid, where each dash is replaced by a digit, indicating the number of mines immediately adjacent to the spot i.e. (horizontally, vertically, and diagonally).",
    recommendations: ["userID_1", "userID_2"],
    tags: ["react.js", "input"],
    user: "userID_B",
    date: new Date(),
    isAnswer: false,
    parentQuestion: null,
  },
  {
    qnaId: "q9",
    title: "리액트로 검색 기능을 어떻게 구현할 수 있나요? 궁금해요",
    content:
      "이번 팀 프로젝트에서 검색 기능을 구현하게 되었는데 그냥 단순히 array.filter를 활용해 검색 기능을 구현하는 방법 말고 더 나은 방법이나 다른 방법에 대해 조언해주실 것이 있나요.",
    recommendations: [
      "userID_1",
      "userID_2",
      "userID_3",
      "userID_4",
      "userID_5",
      "userID_6",
      "userID_7",
      "userID_8",
      "userID_9",
      "userID_10",
      "userID_11",
      "userID_12",
      "userID_13",
      "userID_14",
      "userID_15",
    ],
    tags: ["react.js", "filter", "검색", "search"],
    user: "userID_C",
    date: new Date(),
    isAnswer: false,
    parentQuestion: null,
  },
  {
    qnaId: "q10",
    title: "대충 이렇게 하시면 됩니다. 아래 코드 첨부",
    content:
      "이렇게 저렇게 하고 저렇게 이렇게 하면 짠하고 됩니다. 이렇게 저렇게 하고 저렇게 이렇게 하면 짠하고 됩니다.  이렇게 저렇게 하고 저렇게 이렇게 하면 짠하고 됩니다. 이렇게 저렇게 하고 저렇게 이렇게 하면 짠하고 됩니다. 이렇게 저렇게 하고 저렇게 이렇게 하면 짠하고 됩니다.",
    recommendations: ["userID_1", "userID_2", "userID_12", "userID_13", "userID_14", "userID_15"],
    tags: [
      "react-editor-js",
      "emotion.js",
      "Editor.js",
      "next.js",
      "async",
      "examples",
      "에디터",
      "이미지",
    ],
    user: "userID_C",
    date: new Date(),
    isAnswer: true,
    parentQuestion: "q5",
  },
  {
    qnaId: "qna11",
    title: "이렇게 해보세요",
    content:
      "이렇게 저렇게 하고 저렇게 이렇게 하면 짠하고 됩니다. 이렇게 저렇게 하고 저렇게 이렇게 하면 짠하고 됩니다.  이렇게 저렇게 하고 저렇게 이렇게 하면 짠하고 됩니다. 이렇게 저렇게 하고 저렇게 이렇게 하면 짠하고 됩니다. 이렇게 저렇게 하고 저렇게 이렇게 하면 짠하고 됩니다.",
    recommendations: ["userID_1", "userID_2", "userID_12", "userID_13", "userID_14", "userID_15"],
    tags: [
      "react-editor-js",
      "emotion.js",
      "Editor.js",
      "next.js",
      "async",
      "examples",
      "에디터",
      "이미지",
    ],
    user: "userID_C",
    date: new Date(),
    isAnswer: true,
    parentQuestion: "q5",
  },
];
