export const dummy_qna = [
  {
    qnaId: "q1",
    title: "How to use google analytics with next.js app?",
    content: `{"time":1657466236094,"blocks":[{"id":"6J4jJSRdNI","type":"paragraph","data":{"text":"My Question: I'm using styled-components with next.js so my styles need to be server-side rendered, hence how can I add google analytics to my website? I checked next.js google analytics example but as I said my _document file is different because of using styled-components."}}],"version":"2.25.0"}`,
    recommendations: [
      "userID_1",
      "userID_2",
      "userID_3",
      "userID_4",
      "userID_5",
      "userID_6",
      "userID_7",
      "userID_8",
      "userID_9",
      "userID_10",
    ],
    tags: ["next.js", "styled-components", "google-analytics"],
    user: "userID_A",
    date: new Date(),
    isAnswer: false,
    parentQuestion: null,
  },
  {
    qnaId: "q2",
    title: "ReactJS - Can't type on input fields",
    content: `{"time":1657474477575,"blocks":[{"id":"RY3Mai2z2h","type":"paragraph","data":{"text":"I'm having an issue with the typing on input fields.. i'm working on a big project, which already had other input fields, which were working at the time i wrote them.."}},{"id":"aUa5m4fvf0","type":"paragraph","data":{"text":"today i was adding new fields and noticed that the old fields didn't accept any kind of input. I know this a common question, but my problem is neither not having the value or the onChange set.  Here is a example of the new fields i was working on."}}],"version":"2.25.0"}`,
    recommendations: [
      "userID_1",
      "userID_2",
      "userID_3",
      "userID_4",
      "userID_5",
      "userID_6",
      "userID_7",
      "userID_8",
    ],
    tags: ["react.js", "input"],
    user: "userID_B",
    date: new Date(),
    isAnswer: false,
    parentQuestion: null,
  },
  {
    qnaId: "q3",
    title: "Python data structures 2D lists",
    content: `{"time":1657474536612,"blocks":[{"id":"rLJ8JKuZOA","type":"header","data":{"text":"안녕하세요","level":1}},{"id":"4_lv6sobFS","type":"paragraph","data":{"text":"Here is the question:Create a function that takes a grid of # and -, where each hash (#) represents a mine and each dash (-) represents a mine-free spot. Return a grid, where each dash is replaced by a digit, indicating the number of mines immediately adjacent to the spot i.e. (horizontally, vertically, and diagonally)."}},{"id":"Dfoilb66_l","type":"paragraph","data":{"text":"Here is the question:Create a function that takes a grid of # and -, where each hash (#) represents a mine and each dash (-) represents a mine-free spot. Return a grid, where each dash is replaced by a digit, indicating the number of mines immediately adjacent to the spot i.e. (horizontally, vertically, and diagonally)."}}],"version":"2.25.0"}`,
    recommendations: ["userID_1", "userID_2"],
    tags: ["react.js", "input"],
    user: "userID_B",
    date: new Date(),
    isAnswer: false,
    parentQuestion: null,
  },
  {
    qnaId: "q4",
    title: "리액트로 검색 기능을 어떻게 구현할 수 있나요?",
    content: `{"time":1657474648030,"blocks":[{"id":"rLJ8JKuZOA","type":"header","data":{"text":"안녕하세요","level":1}},{"id":"AVlVmhvVo0","type":"paragraph","data":{"text":"이번 팀 프로젝트에서 검색 기능을 구현하게 되었는데 그냥 단순히 <code class=\"inline-code\">array.filter</code>를 활용해 검색 기능을 구현하는 방법 말고 더 나은 방법이나 다른 방법에 대해 조언해주실 것이 있나요."}},{"id":"0na_CpEc4q","type":"paragraph","data":{"text":"검색 기능 이외에도 구현할 만한 기능에 대해 예시를 들어주시면 감사하겠습니다."}},{"id":"pwxZa-rzUU","type":"list","data":{"style":"unordered","items":["무한 스크롤","답변 추천 기능","자신이 쓴 글 수정, 삭제 기능"]}}],"version":"2.25.0"}`,
    recommendations: [
      "userID_1",
      "userID_2",
      "userID_3",
      "userID_4",
      "userID_5",
      "userID_6",
      "userID_7",
      "userID_8",
      "userID_9",
      "userID_10",
      "userID_11",
      "userID_12",
      "userID_13",
      "userID_14",
      "userID_15",
    ],
    tags: ["react.js", "filter", "검색", "search"],
    user: "userID_C",
    date: new Date(),
    isAnswer: false,
    parentQuestion: null,
  },
  {
    qnaId: "q5",
    title:
      "react-editor-js를 활용해서 에디터를 구현하고자 하는데 이미지가 제대로 저장이 안되네요ㅠㅠ",
    content: `{"time":1657474758580,"blocks":[{"id":"O3p2H9GFBL","type":"header","data":{"text":"react-editor-js 활용법","level":2}},{"id":"-9QNZAXlM_","type":"paragraph","data":{"text":"<code class=\"inline-code\">react-editor-js</code>를 활용해서 에디터를 구현하고자 하는데 이미지가 제대로 저장이 안되네요ㅠㅠ 어떻게 하면 좋을 지 예시를 들어주시면 감사하겠습니다."}},{"id":"scu9JHAYzQ","type":"code","data":{"code":"import { BackTop } from \"antd\";\nimport React from \"react\";\n\nconst TopButton = () => (\n  <>\n    <BackTop />\n  </>\n);\n\nexport default TopButton;\n"}}],"version":"2.25.0"}`,
    recommendations: ["userID_1", "userID_2", "userID_12", "userID_13", "userID_14", "userID_15"],
    tags: [
      "react-editor-js",
      "emotion.js",
      "Editor.js",
      "next.js",
      "async",
      "examples",
      "에디터",
      "이미지",
    ],
    user: "userID_C",
    date: new Date(),
    isAnswer: false,
    parentQuestion: null,
  },
  {
    qnaId: "q6",
    title: "22222222222222 How to use google analytics with next.js app?",
    content:
      "I'm using styled-components with next.js so my styles need to be server-side rendered, hence how can I add google analytics to my website? I checked next.js google analytics example but as I said my _document file is different because of using styled-components.",
    recommendations: [
      "userID_1",
      "userID_2",
      "userID_3",
      "userID_4",
      "userID_5",
      "userID_6",
      "userID_7",
      "userID_8",
      "userID_9",
      "userID_10",
    ],
    tags: ["next.js", "styled-components", "google-analytics"],
    user: "userID_A",
    date: new Date(),
    isAnswer: false,
    parentQuestion: null,
  },
  {
    qnaId: "q7",
    title: "22222222222 ReactJS - Can't type on input fields",
    content:
      "I'm having an issue with the typing on input fields.. i'm working on a big project, which already had other input fields, which were working at the time i wrote them.. today i was adding new fields and noticed that the old fields didn't accept any kind of input. I know this a common question, but my problem is neither not having the value or the onChange set.  Here is a example of the new fields i was working on.",
    recommendations: [
      "userID_1",
      "userID_2",
      "userID_3",
      "userID_4",
      "userID_5",
      "userID_6",
      "userID_7",
      "userID_8",
    ],
    tags: ["react.js", "input"],
    user: "userID_B",
    date: new Date(),
    isAnswer: false,
    parentQuestion: null,
  },
  {
    qnaId: "q8",
    title: "2222222222 Python data structures 2D lists",
    content:
      "Here is the question:Create a function that takes a grid of # and -, where each hash (#) represents a mine and each dash (-) represents a mine-free spot. Return a grid, where each dash is replaced by a digit, indicating the number of mines immediately adjacent to the spot i.e. (horizontally, vertically, and diagonally).",
    recommendations: ["userID_1", "userID_2"],
    tags: ["react.js", "input"],
    user: "userID_B",
    date: new Date(),
    isAnswer: false,
    parentQuestion: null,
  },
  {
    qnaId: "q9",
    title: "리액트로 검색 기능을 어떻게 구현할 수 있나요? 궁금해요",
    content:
      "이번 팀 프로젝트에서 검색 기능을 구현하게 되었는데 그냥 단순히 array.filter를 활용해 검색 기능을 구현하는 방법 말고 더 나은 방법이나 다른 방법에 대해 조언해주실 것이 있나요.",
    recommendations: [
      "userID_1",
      "userID_2",
      "userID_3",
      "userID_4",
      "userID_5",
      "userID_6",
      "userID_7",
      "userID_8",
      "userID_9",
      "userID_10",
      "userID_11",
      "userID_12",
      "userID_13",
      "userID_14",
      "userID_15",
    ],
    tags: ["react.js", "filter", "검색", "search"],
    user: "userID_C",
    date: new Date(),
    isAnswer: false,
    parentQuestion: null,
  },
  {
    qnaId: "q10",
    title: "대충 이렇게 하시면 됩니다. 아래 코드 첨부",
    content:
      '{"time":1657464055584,"blocks":[{"id":"vjicQBfFlG","type":"paragraph","data":{"text":"질문입니다. 질문입니다질문입니다. 질문입니다질문입니다. 질문입니다질문입니다. 질문입니다질문입니다. 질문입니다질문입니다. 질문입니다질문입니다. 질문입니다질문입니다. 질문입니다질문입니다. 질문입니다질문입니다. 질문입니다질문입니다. 질문입니다질문입니다. 질문입니다질문입니다. 질문입니다질문입니다. 질문입니다"}}],"version":"2.25.0"}',
    recommendations: ["userID_1", "userID_2", "userID_12", "userID_13", "userID_14", "userID_15"],
    tags: [
      "react-editor-js",
      "emotion.js",
      "Editor.js",
      "next.js",
      "async",
      "examples",
      "에디터",
      "이미지",
    ],
    user: "userID_C",
    date: new Date(),
    isAnswer: true,
    parentQuestion: "q5",
  },
  {
    qnaId: "qna11",
    title: "이렇게 해보세요",
    content:
      '{"time":1657464055584,"blocks":[{"id":"vjicQBfFlG","type":"paragraph","data":{"text":"질문입니다. 질문입니다질문입니다. 질문입니다질문입니다. 질문입니다질문입니다. 질문입니다질문입니다. 질문입니다질문입니다. 질문입니다질문입니다. 질문입니다질문입니다. 질문입니다질문입니다. 질문입니다질문입니다. 질문입니다질문입니다. 질문입니다질문입니다. 질문입니다질문입니다. 질문입니다질문입니다. 질문입니다"}}],"version":"2.25.0"}',
    recommendations: ["userID_1", "userID_2", "userID_12", "userID_13", "userID_14", "userID_15"],
    tags: [
      "react-editor-js",
      "emotion.js",
      "Editor.js",
      "next.js",
      "async",
      "examples",
      "에디터",
      "이미지",
    ],
    user: "userID_C",
    date: new Date(),
    isAnswer: true,
    parentQuestion: "q5",
  },
];
